addons:
  sonarcloud:
    organization: "knowledgeassets"
    token:
      secure: $SONAR_TOKEN
language: java
jdk: openjdk11
script:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- sonar-scanner
- ./mvnw prepare-package -B -Ptravis
after_success:
- bash <(curl -s https://codecov.io/bash)