addons:
  sonarcloud:
    organization: "knowledgeassets"
    token:
      secure: $SONAR_TOKEN
language: java
jdk: openjdk11
script:
- ./mvnw install sonar:sonar -Ptravis -Dmaven.javadoc.skip=true -B -V
after_success:
- bash <(curl -s https://codecov.io/bash)