logging:
  level:
    # Set overall log level to warning by default.
    root: WARN
    # Set MySkills log level to info by default.
    io.knowledgeassets.myskills.server: INFO
  # Default log file name.
  file: logs/myskills-server.log

spring:
  data:
    neo4j:
      # Set database URI
      uri: ${SPRING_DATA_NEO4J_URI}