logging:
  level:
    # Set overall log level to warning by default.
    root: WARN
    # Set SKOOP log level to info by default.
    com.tsmms.skoop: INFO
  # Default log file name.
  file: logs/skoop-server.log

spring:
  data:
    neo4j:
      # Set database URI
      uri: ${SPRING_DATA_NEO4J_URI}
      password: ${SPRING_DATA_NEO4J_PASSWORD}
      username: ${SPRING_DATA_NEO4J_USERNAME}
  datasource:
    url: jdbc:neo4j:${SPRING_DATA_NEO4J_URI}
    username: ${SPRING_DATA_NEO4J_USERNAME}
    password: ${SPRING_DATA_NEO4J_PASSWORD}

security:
  oauth2:
    resourceserver:
      jwt:
        # Set issuer URI
        jwk-set-uri: ${SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI}
