spring:
  data:
    neo4j:
      # Set database URI to local server.
      uri: 'bolt://localhost:7687'
  datasource:
    url: jdbc:neo4j:bolt://localhost:7687

logging:
  level:
    root: INFO
    com.tsmms.skoop: DEBUG

security:
  oauth2:
    resourceserver:
      jwt:
        # Set issuer URI to local server.
        issuer-uri: 'http://localhost:9000/auth/realms/SKOOP'
