security:
  oauth2:
    resource:
      jwk:
        # Test URL to retrieve the public key for ID token validation.
        key-set-uri: http://localhost:9000/auth/realms/MySkills/protocol/openid-connect/certs
