spring:
  data:
    neo4j:
      # Dumps the generated constraints and indexes to a file
      auto-index: dump
      dump-dir: .
      dump-filename: generated_indexes.cql
      # Set database URI to local server.
      uri: 'bolt://localhost:7687'

logging:
  level:
    root: INFO
    io.knowledgeassets.myskills.server: DEBUG

security:
  oauth2:
    resourceserver:
      jwt:
        # Set issuer URI to local server.
        issuer-uri: 'http://localhost:9000/auth/realms/MySkills'
