spring:
  data:
    neo4j:
      # Auto-create indexes and constraints during development.
      auto-index: update

logging:
  level:
    root: INFO
    io.knowledgeassets.myskills.server: DEBUG

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:9000/auth/realms/MySkills
