spring:
  data:
    neo4j:
      # Automatically create and update indexes and constraints.
      auto-index: update
      # Set database URI to local server.
      uri: 'bolt://localhost:7687'

logging:
  level:
    root: INFO
    io.knowledgeassets.myskills.server: DEBUG

security:
  oauth2:
    resourceserver:
      jwt:
        # Set issuer URI to local server.
        issuer-uri: 'http://localhost:9000/auth/realms/MySkills'
