spring:
  profiles:
    # Enable "dev" profile by default.
    active: dev
  main:
    # Disable banner by default.
    banner-mode: 'off'

security:
  oauth2:
    resource:
      # Default client ID to be used to identify this application in the authorization server.
      id: myskills
      service-id: myskills

springfox:
  documentation:
    swagger:
      v2:
        # Default path to generated OpenAPI specification.
        path: /api-spec

myskills:
  security:
    # List of roles granted to all users by default.
    default-roles:
      - ROLE_USER

logging:
  # Default logging patterns.
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} Request:%X{RequestId} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- Request:%X{RequestId} [%t] %-40.40logger{39} : %m%n%wEx'
