security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: https://auth.example.com/.well-known/jwks.json

spring:
  data:
    neo4j:
      # Set database URI to local embedded server with bolt connector available.
      uri: 'bolt://localhost:7324'
  datasource:
    url: jdbc:neo4j:bolt://localhost:7324
  mail:
    host: localhost # SMTP server
    port: 25 # SMTP port
