spring:
  batch:
    job:
      # Prevent Spring Boot to trigger the Spring Batch Job automatically
      enabled: false

security:
  oauth2:
    resource:
      # Client ID to be used to identify this application in the authorization server
      id: myskills
      jwk:
        # URL to retrieve the public key for ID token validation from
        key-set-uri: http://localhost:9000/auth/realms/MySkills/protocol/openid-connect/certs
      service-id: myskills

springfox:
  documentation:
    swagger:
      v2:
        path: /api-spec

myskills:
  security:
    # Roles granted to users by default
    default-roles:
      - ROLE_USER
